stages:
- name: test1
  steps:
  - runScriptConfig:
      image: ubuntu
      shellScript: date
- name: image
  steps:
  - publishImageConfig:
      dockerfilePath: ./src/Dockerfile
      buildContext: .
      tag: kingsd/cici-test:v1
      registry: 127.0.0.1:34688
timeout: 60
notification: {}
